### ISSUE TITLE
Switch to/provide a version with openjdk8

### ISSUE THREAD

**Issue by gauravsuman007** [mietzen/megabasterd-docker#8]
Good to see that you've created an automated setup, my project was a pain to maintain.

I would suggest moving to openjdk8 or at least providing a separate tag for it as higher jdk versions are much bigger in size (60-70 MB size difference in the final compressed image and that will also translate to the RAM usage)

**Comment by mietzen** [comment]
> MegaBasterd jar version requires [Java 11 or later](https://adoptium.net/es/temurin/releases/?version=11) (at the moment it works in Java 8 but it is not guaranteed)

I mainly chose JRE-17 because I wanted to future proof this project. For me this is 90% fire and forget. I wanted a Image that is regular updated and unlikely to break. This is also the reason why I dropped 32 Bit, alpine 32 bit Java is such a pain to maintain.

I’ll have a look at it, but most likely I am not going to implement JRE-8, because I want this project as lean as possible.
